### ISSUE TITLE
small issue about auto generated tex template

### ISSUE THREAD

**Issue by lyyc199586** [ltrujello/Tikz-Python#1]
A weired thing is the auto generated tex have
```
\usetikzlibrary{

    hobby, decorations.pathreplacing, decorations.markings

}
```
which gives me an error, this can be fixed by remove the blank line:
```
\usetikzlibrary{

    hobby, decorations.pathreplacing, decorations.markings
}
```

But I dont know why it generates a blank line in `\usetikzlibrary` ...

**Comment by ltrujello** [comment]
Interesting, thank you for letting me know! If you'd want to you can submit a pull request and I'll merge it in, otherwise I'll fix this sometime soon.
